name: Deploy odoc to GitHub Pages

on:
  push:
    branches:
      - main

permissions: read-all

concurrency:
  group: deploy-odoc
  cancel-in-progress: true

jobs:
  deploy-odoc:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      id-token: write
      pages: write

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0

      - name: Install dependencies
        run: opam install . --deps-only --with-doc

      - name: Build documentation
        run: |
          opam exec -- dune build @doc
          mkdir -p _build/default/_doc/_html
          # If documentation was built but in a different location, copy it
          if [ -d "_build/default/_doc" ] && [ ! -d "_build/default/_doc/_html" ]; then
            find _build/default/_doc -type f -name "*.html" -exec cp --parents {} _build/default/_doc/_html \;
          fi

      - name: Set-up Pages
        uses: actions/configure-pages@v4

      - name: Debug documentation build
        run: |
          ls -la _build/default/_doc/ || echo "Documentation directory does not exist"
          ls -la _build/default/_doc/_html/ || echo "HTML directory does not exist"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/default/_doc/_html

      - name: Deploy odoc to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
